import dotenv from 'dotenv'
import path from 'path';
dotenv.config({ path: path.resolve(__dirname, '../.env') });

const env = {
    DASHBOARD_URL: process.env.NEXT_DASHBOARD_URL!,
    LANDING_SITE_URL: process.env.NEXT_SITE_URL!,

    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY!,
    CLERK_SECRET_KEY: process.env.NEXT_PUBLIC_CLERK_SECRET_KEY!,
    NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL!,
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL!,
    NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL!,
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL!,

    ENV: process.env.ENV!,

    DATABASE_URL: process.env.DATABASE_URL!,
    DATABASE_ACCESS_TOKEN: process.env.DATABASE_AUTH_TOKEN!,
};

export const {
    DASHBOARD_URL,
    DATABASE_ACCESS_TOKEN,
    LANDING_SITE_URL,
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
    NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL,
    NEXT_PUBLIC_CLERK_SIGN_IN_URL,
    NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL,
    NEXT_PUBLIC_CLERK_SIGN_UP_URL,
    CLERK_SECRET_KEY,
    ENV,
} = env;

export { env };